### Check API health
GET http://localhost:3000


### Get all users
GET http://localhost:3000/users

### Users with query param
GET http://localhost:3000/users?role=ADMIN

### Get user by ID
GET http://localhost:3000/users/6

### Get all interns
GET http://localhost:3000/users/interns


### Create a new user
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Nikhil",
    "email": "nikhil@gmail.com",
    "role": "ADMIN"
}


### Update a user
PATCH http://localhost:3000/users/6
Content-Type: application/json

{
    "name": "Nikhil 123"
}
